name: Deploy Web
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'web/**/*'
      - '.github/workflows/web.workflow.yml'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm --prefix web ci
      - name: Build
        run: npm run build:web
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'jms-docs'
